// <auto-generated />
using System;
using Kursach_Backend.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kursach_Backend.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260428102456_Tables2")]
    partial class Tables2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kursach_Backend.Models.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MidleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublicationEditionId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PublicationEditionId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.PublicationEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EditionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PublicationEditions");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.PublicationFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PublicationFiles");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.ScientificPublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Doi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublicationEditionId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PublicationEditionId");

                    b.ToTable("ScientificPublications");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.Publication", b =>
                {
                    b.HasOne("Kursach_Backend.Models.Employees.Employee", null)
                        .WithMany("Publications")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Kursach_Backend.Models.Employees.PublicationEdition", "PublicationEdition")
                        .WithMany("Publications")
                        .HasForeignKey("PublicationEditionId");

                    b.Navigation("PublicationEdition");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.PublicationFile", b =>
                {
                    b.HasOne("Kursach_Backend.Models.Employees.Employee", null)
                        .WithMany("PublicationFiles")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.ScientificPublication", b =>
                {
                    b.HasOne("Kursach_Backend.Models.Employees.Employee", null)
                        .WithMany("ScientificPublications")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Kursach_Backend.Models.Employees.PublicationEdition", "PublicationEdition")
                        .WithMany()
                        .HasForeignKey("PublicationEditionId");

                    b.Navigation("PublicationEdition");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.Employee", b =>
                {
                    b.Navigation("PublicationFiles");

                    b.Navigation("Publications");

                    b.Navigation("ScientificPublications");
                });

            modelBuilder.Entity("Kursach_Backend.Models.Employees.PublicationEdition", b =>
                {
                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
